# Generated by Django 6.0 on 2026-01-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
                ('vencedor', models.CharField(choices=[('A', 'Time A'), ('B', 'Time B')], max_length=1)),
                ('placar_final_a', models.PositiveSmallIntegerField()),
                ('placar_final_b', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
